version: '3.5'

services:

  immobile-api:
    build:
      dockerfile: Dockerfile
      context: .
    image: immobile-api:latest
    container_name: immobile-api-docker
    restart: always
    ports:
        - ${PORT}:${PORT}
    expose: 
        - ${PORT}
    command: npm run start:prod
    logging:
      options:
        max-size: "10m"
        max-file: "3"